#ifndef RANDOM_SAMPLING_H
#define RANDOM_SAMPLING_H

#include "parameters.h"
#include "polyvec.h"
#include "poly.h"


// Derived from https://github.com/PQClean/PQClean/blob/master/crypto_kem/ml-kem-512/clean

# define CBD3_BYTES (3*DKE1_N/4)

/// @brief generates a polynomial in Rq according to the centered binomial distribution
/// with parameter eta = 3.
/// @param[in]  coins   random coins array (we need 3 * DKE1_N / 4 bytes
/// since eta random bytes ----> 4 random coeffs in {-eta, ..., eta}):
/// @param[out] pol     pointer to output polynomial
void centered_binomial3(poly* pol, const unsigned char coins[CBD3_BYTES]);


// As used in the protocol:

// TODO: comment
void DKE1_cbdA(poly* pol, const unsigned char coins[CBD3_BYTES]);
void DKE1_cbdB(poly* pol, const unsigned char coins[CBD3_BYTES]);

// TODO: comment
void DKE1_getsecretA(poly* pol, const unsigned char rand[DKE1_SEEDBYTES], const uint8_t nonce);
void DKE1_geterrorA(poly* pol, const unsigned char rand[DKE1_SEEDBYTES], const uint8_t nonce);
void DKE1_getsecretB(poly* pol, const unsigned char rand[DKE1_SEEDBYTES], const uint8_t nonce);
void DKE1_geterrorB(poly* pol, const unsigned char rand[DKE1_SEEDBYTES], const uint8_t nonce);

// ---------------------------------------------------------------------------
// Random sampling in Zq:

/// @brief Run rejection sampling on uniform random bytes to generate
///        uniform random integers mod q.
/// @param[in]  len      requested number of 16-bit integers (uniform mod q)
/// @param[in]  buf      pointer to input buffer (assumed to be uniformly random bytes)
/// @param[in]  buflen   length of input buffer in bytes
/// @param[out] res      pointer to output buffer
/// @return     number of sampled 16-bit integers (at most len)
unsigned int rej_uniform(int16_t *res,
                         const unsigned int len,
                         const unsigned char *buf,
                         unsigned int buflen);

// ---------------------------------------------------------------------------
// Random sampling in Rq:

/// @brief Deterministically samples a polynomial with coefficients
///        uniformly distributed in Z_q from (seed || i || j).
///
/// The function expands the input seed using pseudoXOF and applies
/// rejection sampling to obtain coefficients in R_q.
/// @param[in] seed     random seed
/// @param[in] i        used to modify seed
/// @param[in] j        used to modify seed
/// @param[out] pol     pointer to output polynomial pol in Rq
void poly_uniform(poly* pol,
                  const uint8_t seed[DKE1_SEEDBYTES],
                  const uint8_t i,
                  const uint8_t j);


/// @brief Deterministically generates the matrix M ∈ R_q^(k×k)
///        from a seed.
///
/// Each polynomial entry of the matrix is generated by invoking
/// poly_uniform with domain separation parameters derived from
/// the matrix indices.
///
/// @param[in]  seed         random seed
/// @param[in]  transposed   if zero, the function samples M. If not zero, it samples M^t.
/// @param[out] res          pointer to output consisting on k vectors of polynomials (namely a matrix M over Rq)
/* TODO: Optimize this function.
 * The implementation of this function is not efficient yet (in the sense of
  minimizing the number of BYTES derived from pseudoXOF). I changed the implementation
  of this function with respect to PQClean -letting the auxiliar function poly_uniform
  to handle pseudoXOF- because we are using a XOF provided by ICCS,
  with a different interface with respect to SHAKE */
#define gen_a(A,B)  DKE1_gen_matrix(A,B,0)
#define gen_at(A,B) DKE1_gen_matrix(A,B,1)
void DKE1_gen_matrix(polyvec *res,
                     const uint8_t seed[DKE1_SEEDBYTES],
                     const int transposed);



#endif //RANDOM_SAMPLING_H
